modLoader="javafml"
loaderVersion="[33,)"
license="\u00A77\u00A7lThe \u00A74\u00A7lMIT \u00A77\u00A7lLicence\u00A7r (MIT)"
issueTrackerURL="https://github.com/CabicCraft/CabicCraft/issues"

[[mods]]
    modId="cabiccraft"
    version="\u00A710\u00A7r.\u00A793\u00A7r.\u00A7b1\u00A7r\u00A7c"
    displayName="CabicCraft"
    #updateJSONURL=""
    displayURL="https://github.com/CabicCraft/CabicCraft/"
    logoFile="cabiccraftbanner.png"
    credits="Forge, and the Modding Community!"
    authors="\u00A72Cubicpath"
    description=''''''

    [[dependencies.cabiccraft]]
        modId="forge"
        mandatory=true
        versionRange="[33,)"
        ordering="NONE"
        side="BOTH"
    [[dependencies.cabiccraft]]
        modId="minecraft"
        mandatory=true
        versionRange="[1.16.2]"
        ordering="NONE"
        side="BOTH"
